"""
Script one-time para completar datos de selecciones nacionales:
coach, ciudad del estadio, capacidad, historial mundialista.

cd backend && python3 -m app.scripts.seed_team_data
"""

from sqlalchemy import select
from sqlalchemy.orm import Session
from app.core.db import engine
from app.models.team import Team

# code -> datos a actualizar
TEAM_DATA = {
    "GER": {
        "coach_name": "Julian Nagelsmann",
        "coach_nationality": "Alemán",
        "venue_name": "Olympiastadion Berlin",
        "venue_city": "Berlín",
        "venue_capacity": 74064,
        "first_wc_year": 1934,
        "wc_participations": 20,
        "wc_played": 106,
        "wc_wins": 67,
        "wc_draws": 21,
        "wc_losses": 18,
        "wc_goals_scored": 226,
        "wc_goals_conceded": 125,
    },
    "ARG": {
        "coach_name": "Lionel Scaloni",
        "coach_nationality": "Argentino",
        "venue_name": "Estadio Más Monumental",
        "venue_city": "Buenos Aires",
        "venue_capacity": 84567,
        "first_wc_year": 1930,
        "wc_participations": 18,
        "wc_played": 83,
        "wc_wins": 45,
        "wc_draws": 17,
        "wc_losses": 21,
        "wc_goals_scored": 137,
        "wc_goals_conceded": 99,
    },
    "BRA": {
        "coach_name": "Dorival Júnior",
        "coach_nationality": "Brasileño",
        "venue_name": "Maracanã",
        "venue_city": "Río de Janeiro",
        "venue_capacity": 78838,
        "first_wc_year": 1930,
        "wc_participations": 22,
        "wc_played": 109,
        "wc_wins": 73,
        "wc_draws": 19,
        "wc_losses": 17,
        "wc_goals_scored": 232,
        "wc_goals_conceded": 102,
    },
    "FRA": {
        "coach_name": "Didier Deschamps",
        "coach_nationality": "Francés",
        "venue_name": "Stade de France",
        "venue_city": "Saint-Denis",
        "venue_capacity": 81338,
        "first_wc_year": 1930,
        "wc_participations": 16,
        "wc_played": 66,
        "wc_wins": 34,
        "wc_draws": 13,
        "wc_losses": 19,
        "wc_goals_scored": 120,
        "wc_goals_conceded": 76,
    },
    "ESP": {
        "coach_name": "Luis de la Fuente",
        "coach_nationality": "Español",
        "venue_name": "Santiago Bernabéu",
        "venue_city": "Madrid",
        "venue_capacity": 81044,
        "first_wc_year": 1934,
        "wc_participations": 16,
        "wc_played": 63,
        "wc_wins": 31,
        "wc_draws": 12,
        "wc_losses": 20,
        "wc_goals_scored": 99,
        "wc_goals_conceded": 77,
    },
    "ENG": {
        "coach_name": "Thomas Tuchel",
        "coach_nationality": "Alemán",
        "venue_name": "Wembley Stadium",
        "venue_city": "Londres",
        "venue_capacity": 90000,
        "first_wc_year": 1950,
        "wc_participations": 16,
        "wc_played": 69,
        "wc_wins": 30,
        "wc_draws": 20,
        "wc_losses": 19,
        "wc_goals_scored": 91,
        "wc_goals_conceded": 71,
    },
    "NED": {
        "coach_name": "Ronald Koeman",
        "coach_nationality": "Neerlandés",
        "venue_name": "Johan Cruijff ArenA",
        "venue_city": "Ámsterdam",
        "venue_capacity": 54990,
        "first_wc_year": 1934,
        "wc_participations": 11,
        "wc_played": 52,
        "wc_wins": 28,
        "wc_draws": 8,
        "wc_losses": 16,
        "wc_goals_scored": 93,
        "wc_goals_conceded": 64,
    },
    "POR": {
        "coach_name": "Roberto Martínez",
        "coach_nationality": "Español",
        "venue_name": "Estádio da Luz",
        "venue_city": "Lisboa",
        "venue_capacity": 65647,
        "first_wc_year": 1966,
        "wc_participations": 9,
        "wc_played": 37,
        "wc_wins": 17,
        "wc_draws": 7,
        "wc_losses": 13,
        "wc_goals_scored": 61,
        "wc_goals_conceded": 42,
    },
    "BEL": {
        "coach_name": "Rudi García",
        "coach_nationality": "Francés",
        "venue_name": "King Baudouin Stadium",
        "venue_city": "Bruselas",
        "venue_capacity": 50093,
        "first_wc_year": 1930,
        "wc_participations": 14,
        "wc_played": 45,
        "wc_wins": 17,
        "wc_draws": 11,
        "wc_losses": 17,
        "wc_goals_scored": 65,
        "wc_goals_conceded": 61,
    },
    "CRO": {
        "coach_name": "Zlatko Dalić",
        "coach_nationality": "Croata",
        "venue_name": "Stadion Maksimir",
        "venue_city": "Zagreb",
        "venue_capacity": 35123,
        "first_wc_year": 1998,
        "wc_participations": 6,
        "wc_played": 25,
        "wc_wins": 13,
        "wc_draws": 4,
        "wc_losses": 8,
        "wc_goals_scored": 35,
        "wc_goals_conceded": 26,
    },
    "SUI": {
        "coach_name": "Murat Yakin",
        "coach_nationality": "Suizo",
        "venue_name": "St. Jakob-Park",
        "venue_city": "Basilea",
        "venue_capacity": 38512,
        "first_wc_year": 1934,
        "wc_participations": 12,
        "wc_played": 38,
        "wc_wins": 14,
        "wc_draws": 9,
        "wc_losses": 15,
        "wc_goals_scored": 54,
        "wc_goals_conceded": 59,
    },
    "URU": {
        "coach_name": "Marcelo Bielsa",
        "coach_nationality": "Argentino",
        "venue_name": "Estadio Centenario",
        "venue_city": "Montevideo",
        "venue_capacity": 60235,
        "first_wc_year": 1930,
        "wc_participations": 14,
        "wc_played": 56,
        "wc_wins": 24,
        "wc_draws": 13,
        "wc_losses": 19,
        "wc_goals_scored": 82,
        "wc_goals_conceded": 73,
    },
    "MEX": {
        "coach_name": "Javier Aguirre",
        "coach_nationality": "Mexicano",
        "venue_name": "Estadio Akron",
        "venue_city": "Guadalajara",
        "venue_capacity": 49850,
        "first_wc_year": 1930,
        "wc_participations": 17,
        "wc_played": 57,
        "wc_wins": 16,
        "wc_draws": 15,
        "wc_losses": 26,
        "wc_goals_scored": 67,
        "wc_goals_conceded": 95,
    },
    "USA": {
        "coach_name": "Mauricio Pochettino",
        "coach_nationality": "Argentino",
        "venue_name": "SoFi Stadium",
        "venue_city": "Los Ángeles",
        "venue_capacity": 70240,
        "first_wc_year": 1930,
        "wc_participations": 11,
        "wc_played": 37,
        "wc_wins": 8,
        "wc_draws": 5,
        "wc_losses": 24,
        "wc_goals_scored": 36,
        "wc_goals_conceded": 72,
    },
    "CAN": {
        "coach_name": "Mauro Biello",
        "coach_nationality": "Canadiense",
        "venue_name": "BMO Field",
        "venue_city": "Toronto",
        "venue_capacity": 30000,
        "first_wc_year": 1986,
        "wc_participations": 2,
        "wc_played": 4,
        "wc_wins": 0,
        "wc_draws": 1,
        "wc_losses": 3,
        "wc_goals_scored": 2,
        "wc_goals_conceded": 5,
    },
    "JPN": {
        "coach_name": "Hajime Moriyasu",
        "coach_nationality": "Japonés",
        "venue_name": "Saitama Stadium 2002",
        "venue_city": "Saitama",
        "venue_capacity": 63700,
        "first_wc_year": 1998,
        "wc_participations": 8,
        "wc_played": 25,
        "wc_wins": 8,
        "wc_draws": 6,
        "wc_losses": 11,
        "wc_goals_scored": 30,
        "wc_goals_conceded": 36,
    },
    "AUS": {
        "coach_name": "Tony Popovic",
        "coach_nationality": "Australiano",
        "venue_name": "Accor Stadium",
        "venue_city": "Sídney",
        "venue_capacity": 83500,
        "first_wc_year": 1974,
        "wc_participations": 6,
        "wc_played": 19,
        "wc_wins": 4,
        "wc_draws": 4,
        "wc_losses": 11,
        "wc_goals_scored": 19,
        "wc_goals_conceded": 43,
    },
    "KOR": {
        "coach_name": "Hong Myung-bo",
        "coach_nationality": "Surcoreano",
        "venue_name": "Seoul World Cup Stadium",
        "venue_city": "Seúl",
        "venue_capacity": 66806,
        "first_wc_year": 1954,
        "wc_participations": 11,
        "wc_played": 36,
        "wc_wins": 8,
        "wc_draws": 6,
        "wc_losses": 22,
        "wc_goals_scored": 39,
        "wc_goals_conceded": 76,
    },
    "MAR": {
        "coach_name": "Walid Regragui",
        "coach_nationality": "Marroquí",
        "venue_name": "Stade Mohammed V",
        "venue_city": "Casablanca",
        "venue_capacity": 68000,
        "first_wc_year": 1970,
        "wc_participations": 7,
        "wc_played": 24,
        "wc_wins": 8,
        "wc_draws": 6,
        "wc_losses": 10,
        "wc_goals_scored": 24,
        "wc_goals_conceded": 29,
    },
    "SEN": {
        "coach_name": "Aliou Cissé",
        "coach_nationality": "Senegalés",
        "venue_name": "Stade Abdoulaye Wade",
        "venue_city": "Dakar",
        "venue_capacity": 50000,
        "first_wc_year": 2002,
        "wc_participations": 3,
        "wc_played": 10,
        "wc_wins": 4,
        "wc_draws": 1,
        "wc_losses": 5,
        "wc_goals_scored": 12,
        "wc_goals_conceded": 12,
    },
    "KSA": {
        "coach_name": "Hervé Renard",
        "coach_nationality": "Francés",
        "venue_name": "Estadio Internacional Rey Fahd",
        "venue_city": "Riad",
        "venue_capacity": 68752,
        "first_wc_year": 1994,
        "wc_participations": 7,
        "wc_played": 22,
        "wc_wins": 4,
        "wc_draws": 5,
        "wc_losses": 13,
        "wc_goals_scored": 18,
        "wc_goals_conceded": 44,
    },
    "EGY": {
        "coach_name": "Hossam Hassan",
        "coach_nationality": "Egipcio",
        "venue_name": "El Cairo International Stadium",
        "venue_city": "El Cairo",
        "venue_capacity": 75100,
        "first_wc_year": 1934,
        "wc_participations": 3,
        "wc_played": 8,
        "wc_wins": 2,
        "wc_draws": 0,
        "wc_losses": 6,
        "wc_goals_scored": 6,
        "wc_goals_conceded": 15,
    },
    "COL": {
        "coach_name": "Néstor Lorenzo",
        "coach_nationality": "Argentino",
        "venue_name": "Estadio Metropolitano Roberto Meléndez",
        "venue_city": "Barranquilla",
        "venue_capacity": 47000,
        "first_wc_year": 1962,
        "wc_participations": 7,
        "wc_played": 24,
        "wc_wins": 9,
        "wc_draws": 6,
        "wc_losses": 9,
        "wc_goals_scored": 29,
        "wc_goals_conceded": 29,
    },
    "ECU": {
        "coach_name": "Sebastián Beccacece",
        "coach_nationality": "Argentino",
        "venue_name": "Estadio Rodrigo Paz Delgado",
        "venue_city": "Quito",
        "venue_capacity": 41575,
        "first_wc_year": 2002,
        "wc_participations": 4,
        "wc_played": 13,
        "wc_wins": 4,
        "wc_draws": 3,
        "wc_losses": 6,
        "wc_goals_scored": 14,
        "wc_goals_conceded": 18,
    },
    "PAR": {
        "coach_name": "Gustavo Alfaro",
        "coach_nationality": "Argentino",
        "venue_name": "Estadio Defensores del Chaco",
        "venue_city": "Asunción",
        "venue_capacity": 42354,
        "first_wc_year": 1930,
        "wc_participations": 9,
        "wc_played": 28,
        "wc_wins": 7,
        "wc_draws": 9,
        "wc_losses": 12,
        "wc_goals_scored": 30,
        "wc_goals_conceded": 39,
    },
    "TUR": {
        "coach_name": "Vincenzo Montella",
        "coach_nationality": "Italiano",
        "venue_name": "Atatürk Olympic Stadium",
        "venue_city": "Estambul",
        "venue_capacity": 76092,
        "first_wc_year": 1954,
        "wc_participations": 3,
        "wc_played": 10,
        "wc_wins": 5,
        "wc_draws": 1,
        "wc_losses": 4,
        "wc_goals_scored": 20,
        "wc_goals_conceded": 17,
    },
    "IRN": {
        "coach_name": "Amir Ghalenoei",
        "coach_nationality": "Iraní",
        "venue_name": "Azadi Stadium",
        "venue_city": "Teherán",
        "venue_capacity": 78116,
        "first_wc_year": 1978,
        "wc_participations": 7,
        "wc_played": 21,
        "wc_wins": 2,
        "wc_draws": 3,
        "wc_losses": 16,
        "wc_goals_scored": 13,
        "wc_goals_conceded": 42,
    },
    "NOR": {
        "coach_name": "Ståle Solbakken",
        "coach_nationality": "Noruego",
        "venue_name": "Ullevaal Stadion",
        "venue_city": "Oslo",
        "venue_capacity": 27700,
        "first_wc_year": 1938,
        "wc_participations": 3,
        "wc_played": 7,
        "wc_wins": 2,
        "wc_draws": 1,
        "wc_losses": 4,
        "wc_goals_scored": 7,
        "wc_goals_conceded": 8,
    },
    "SCO": {
        "coach_name": "Steve Clarke",
        "coach_nationality": "Escocés",
        "venue_name": "Hampden Park",
        "venue_city": "Glasgow",
        "venue_capacity": 51866,
        "first_wc_year": 1954,
        "wc_participations": 8,
        "wc_played": 23,
        "wc_wins": 4,
        "wc_draws": 7,
        "wc_losses": 12,
        "wc_goals_scored": 25,
        "wc_goals_conceded": 41,
    },
    "AUT": {
        "coach_name": "Ralf Rangnick",
        "coach_nationality": "Alemán",
        "venue_name": "Ernst-Happel-Stadion",
        "venue_city": "Viena",
        "venue_capacity": 48500,
        "first_wc_year": 1934,
        "wc_participations": 7,
        "wc_played": 26,
        "wc_wins": 12,
        "wc_draws": 4,
        "wc_losses": 10,
        "wc_goals_scored": 43,
        "wc_goals_conceded": 47,
    },
    "SWE": {
        "coach_name": "Jon Dahl Tomasson",
        "coach_nationality": "Danés",
        "venue_name": "Friends Arena",
        "venue_city": "Estocolmo",
        "venue_capacity": 50000,
        "first_wc_year": 1934,
        "wc_participations": 12,
        "wc_played": 46,
        "wc_wins": 16,
        "wc_draws": 10,
        "wc_losses": 20,
        "wc_goals_scored": 74,
        "wc_goals_conceded": 69,
    },
    "GHA": {
        "coach_name": "Otto Addo",
        "coach_nationality": "Alemán",
        "venue_name": "Baba Yara Stadium",
        "venue_city": "Kumasi",
        "venue_capacity": 40528,
        "first_wc_year": 2006,
        "wc_participations": 4,
        "wc_played": 13,
        "wc_wins": 4,
        "wc_draws": 2,
        "wc_losses": 7,
        "wc_goals_scored": 14,
        "wc_goals_conceded": 22,
    },
    "CIV": {
        "coach_name": "Emerse Faé",
        "coach_nationality": "Marfileño",
        "venue_name": "Stade Alassane Ouattara",
        "venue_city": "Abiyán",
        "venue_capacity": 60000,
        "first_wc_year": 2006,
        "wc_participations": 3,
        "wc_played": 9,
        "wc_wins": 2,
        "wc_draws": 1,
        "wc_losses": 6,
        "wc_goals_scored": 7,
        "wc_goals_conceded": 14,
    },
    "TUN": {
        "coach_name": "Jalel Kadri",
        "coach_nationality": "Tunecino",
        "venue_name": "Stade Olympique de Radès",
        "venue_city": "Radès",
        "venue_capacity": 60000,
        "first_wc_year": 1978,
        "wc_participations": 6,
        "wc_played": 18,
        "wc_wins": 2,
        "wc_draws": 5,
        "wc_losses": 11,
        "wc_goals_scored": 11,
        "wc_goals_conceded": 27,
    },
    "ALG": {
        "coach_name": "Vladimir Petkovic",
        "coach_nationality": "Suizo",
        "venue_name": "Stade Nelson Mandela",
        "venue_city": "Argel",
        "venue_capacity": 40258,
        "first_wc_year": 1982,
        "wc_participations": 4,
        "wc_played": 13,
        "wc_wins": 4,
        "wc_draws": 1,
        "wc_losses": 8,
        "wc_goals_scored": 14,
        "wc_goals_conceded": 20,
    },
    "RSA": {
        "coach_name": "Hugo Broos",
        "coach_nationality": "Belga",
        "venue_name": "FNB Stadium",
        "venue_city": "Johannesburgo",
        "venue_capacity": 94736,
        "first_wc_year": 1998,
        "wc_participations": 3,
        "wc_played": 9,
        "wc_wins": 2,
        "wc_draws": 2,
        "wc_losses": 5,
        "wc_goals_scored": 8,
        "wc_goals_conceded": 17,
    },
    "CPV": {
        "coach_name": "Bubista",
        "coach_nationality": "Portugués",
        "venue_name": "Estádio Nacional de Cabo Verde",
        "venue_city": "Praia",
        "venue_capacity": 15000,
        "first_wc_year": 2026,
        "wc_participations": 0,
        "wc_played": 0,
        "wc_wins": 0,
        "wc_draws": 0,
        "wc_losses": 0,
        "wc_goals_scored": 0,
        "wc_goals_conceded": 0,
    },
    "QAT": {
        "coach_name": "Félix Sánchez Bas",
        "coach_nationality": "Español",
        "venue_name": "Estadio Internacional de Khalifa",
        "venue_city": "Doha",
        "venue_capacity": 45857,
        "first_wc_year": 2022,
        "wc_participations": 1,
        "wc_played": 3,
        "wc_wins": 0,
        "wc_draws": 0,
        "wc_losses": 3,
        "wc_goals_scored": 1,
        "wc_goals_conceded": 7,
    },
    "CZE": {
        "coach_name": "Ivan Hašek",
        "coach_nationality": "Checo",
        "venue_name": "Fortuna Arena",
        "venue_city": "Praga",
        "venue_capacity": 19370,
        "first_wc_year": 1934,
        "wc_participations": 9,
        "wc_played": 30,
        "wc_wins": 12,
        "wc_draws": 5,
        "wc_losses": 13,
        "wc_goals_scored": 52,
        "wc_goals_conceded": 47,
    },
    "NZL": {
        "coach_name": "Darren Bazeley",
        "coach_nationality": "Neozelandés",
        "venue_name": "Eden Park",
        "venue_city": "Auckland",
        "venue_capacity": 50000,
        "first_wc_year": 1982,
        "wc_participations": 3,
        "wc_played": 9,
        "wc_wins": 1,
        "wc_draws": 0,
        "wc_losses": 8,
        "wc_goals_scored": 5,
        "wc_goals_conceded": 17,
    },
    "PAN": {
        "coach_name": "Thomas Christiansen",
        "coach_nationality": "Español",
        "venue_name": "Estadio Rommel Fernández",
        "venue_city": "Ciudad de Panamá",
        "venue_capacity": 32000,
        "first_wc_year": 2018,
        "wc_participations": 2,
        "wc_played": 6,
        "wc_wins": 0,
        "wc_draws": 1,
        "wc_losses": 5,
        "wc_goals_scored": 3,
        "wc_goals_conceded": 11,
    },
    "HAI": {
        "coach_name": "Marc Collat",
        "coach_nationality": "Francés",
        "venue_name": "Stade Sylvio Cator",
        "venue_city": "Puerto Príncipe",
        "venue_capacity": 10000,
        "first_wc_year": 1974,
        "wc_participations": 1,
        "wc_played": 3,
        "wc_wins": 0,
        "wc_draws": 0,
        "wc_losses": 3,
        "wc_goals_scored": 2,
        "wc_goals_conceded": 14,
    },
    "CUW": {
        "coach_name": "Remko Bicentini",
        "coach_nationality": "Curazaleño",
        "venue_name": "Stadion Ergilio Hato",
        "venue_city": "Willemstad",
        "venue_capacity": 12000,
        "first_wc_year": 2026,
        "wc_participations": 0,
        "wc_played": 0,
        "wc_wins": 0,
        "wc_draws": 0,
        "wc_losses": 0,
        "wc_goals_scored": 0,
        "wc_goals_conceded": 0,
    },
    "BIH": {
        "coach_name": "Sergej Barbarez",
        "coach_nationality": "Bosnio",
        "venue_name": "Bilino Polje",
        "venue_city": "Zenica",
        "venue_capacity": 15800,
        "first_wc_year": 2014,
        "wc_participations": 2,
        "wc_played": 6,
        "wc_wins": 1,
        "wc_draws": 0,
        "wc_losses": 5,
        "wc_goals_scored": 5,
        "wc_goals_conceded": 13,
    },
    "JOR": {
        "coach_name": "Hussain Amin",
        "coach_nationality": "Jordano",
        "venue_name": "Amman International Stadium",
        "venue_city": "Ammán",
        "venue_capacity": 17419,
        "first_wc_year": 2026,
        "wc_participations": 0,
        "wc_played": 0,
        "wc_wins": 0,
        "wc_draws": 0,
        "wc_losses": 0,
        "wc_goals_scored": 0,
        "wc_goals_conceded": 0,
    },
    "IRQ": {
        "coach_name": "Jesús Casas",
        "coach_nationality": "Español",
        "venue_name": "Basra International Stadium",
        "venue_city": "Basra",
        "venue_capacity": 65000,
        "first_wc_year": 1986,
        "wc_participations": 2,
        "wc_played": 6,
        "wc_wins": 0,
        "wc_draws": 1,
        "wc_losses": 5,
        "wc_goals_scored": 4,
        "wc_goals_conceded": 12,
    },
    "UZB": {
        "coach_name": "Srecko Katanec",
        "coach_nationality": "Esloveno",
        "venue_name": "Milliy Stadium",
        "venue_city": "Taskent",
        "venue_capacity": 35000,
        "first_wc_year": 2026,
        "wc_participations": 0,
        "wc_played": 0,
        "wc_wins": 0,
        "wc_draws": 0,
        "wc_losses": 0,
        "wc_goals_scored": 0,
        "wc_goals_conceded": 0,
    },
    "COD": {
        "coach_name": "Sébastien Desabre",
        "coach_nationality": "Francés",
        "country": "DR Congo",
        "founded": 1919,
        "venue_name": "Stade des Martyrs",
        "venue_city": "Kinshasa",
        "venue_capacity": 80000,
        "first_wc_year": 1974,
        "wc_participations": 2,
        "wc_played": 6,
        "wc_wins": 1,
        "wc_draws": 0,
        "wc_losses": 5,
        "wc_goals_scored": 7,
        "wc_goals_conceded": 22,
    },
}

FIELDS = [
    "coach_name", "coach_nationality", "venue_name", "venue_city", "venue_capacity",
    "first_wc_year", "wc_participations", "wc_played", "wc_wins", "wc_draws",
    "wc_losses", "wc_goals_scored", "wc_goals_conceded", "country", "founded",
]


def main():
    with Session(engine) as db:
        teams = db.execute(select(Team)).scalars().all()
        code_map = {t.code: t for t in teams}

        updated = 0
        skipped = 0
        for code, data in TEAM_DATA.items():
            team = code_map.get(code)
            if not team:
                print(f"  SKIP {code}: no encontrado en DB")
                skipped += 1
                continue

            for field, value in data.items():
                if field in FIELDS:
                    setattr(team, field, value)

            db.add(team)
            print(f"  OK {code} — {team.name}")
            updated += 1

        db.commit()
        print(f"\nActualizados: {updated} | Saltados: {skipped}")


if __name__ == "__main__":
    main()
