services:
  prode_postgres:
    image: postgres:16
    container_name: prode_mundial_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: prode_mundial_db
      POSTGRES_USER: prode_user
      POSTGRES_PASSWORD: prode_pass
    ports:
      - "5440:5432"
    volumes:
      - prode_postgres_data:/var/lib/postgresql/data
    networks:
      - prode_network

  prode_pgadmin:
    image: dpage/pgadmin4:latest
    container_name: prode_mundial_pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@prode.com
      PGADMIN_DEFAULT_PASSWORD: admin123
    ports:
      - "5080:80"
    depends_on:
      - prode_postgres
    networks:
      - prode_network

volumes:
  prode_postgres_data:

networks:
  prode_network:
    driver: bridge